---
name: CI/CD
on: [push, pull_request]
jobs:
  build:
    name: Validate
    runs-on: ubuntu-latest
    container: python:3.7-slim
    steps:
    - name: Checkout master
      uses: actions/checkout@v1.2.0
    - name: Install lxml
      run: python -m pip install lxml==4.3.0
    - name:
      run: python scripts/check_material_profiles_new_with_lxml.py
